version: '3.7'

# This docker-compose file is used for starting all MLS services.
# It does not build anything, but uses locally built images or pulls them from Docker Hub.
# By default the image tagged as 'latest' is pulled. This can be overridden by setting $MLS_TAG
# Configuration is taken from ./config which can be overridden by setting $MLS_CONFIG
# Log files are written to ./log which can be overridden by setting $MLS_LOG

services:
  mls-gateway:
    image: wrkfmdit/mls-gateway:${MLS_TAG:-latest}
    ports:
      - 8090:8080
    volumes:
      - type: bind
        source: ${MLS_CONFIG:-./config}/gateway
        target: /config
        read_only: true
      - type: bind
        source: ${MLS_LOG:-./log}
        target: /log

  mls-auth:
    image: wrkfmdit/mls-auth:${MLS_TAG:-latest}
    volumes:
      - type: bind
        source: ${MLS_CONFIG:-./config}/auth
        target: /config
        read_only: true
      - type: bind
        source: ${MLS_LOG:-./log}
        target: /log

  mls-coceso:
    image: wrkfmdit/mls-coceso:${MLS_TAG:-latest}
    volumes:
      - type: bind
        source: ${MLS_CONFIG:-./config}/coceso
        target: /config
        read_only: true
      - type: bind
        source: ${MLS_LOG:-./log}
        target: /log

  mls-frontend:
    image: wrkfmdit/mls-frontend:${MLS_TAG:-latest}
    links:
      - mls-gateway
    ports:
      - 8089:80

  mls-amqp:
    image: wrkfmdit/mls-amqp:${MLS_TAG:-latest}
    environment:
      RABBITMQ_DEFAULT_USER: mls-rabbitmq-user
      RABBITMQ_DEFAULT_PASS: mls-rabbitmq-pass

  mls-db:
    image: wrkfmdit/mls-db:${MLS_TAG:-latest}
    environment:
      - POSTGRES_USER=mls
      - POSTGRES_PASSWORD=mls-root-password
      - POSTGRES_DATABASES=mls-coceso:mls-coceso-password,mls-auth:mls-auth-password
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  default:
    name: mls-network

volumes:
  postgres-data:
