spring:
  rabbitmq:
    host: mls-amqp
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass

application:
  message:
    type: phone
    sms:
      filter:
        patterns:
          - "\\+436\\d+"
      gateway:
        url: http://mls-message-mock-gateway:8000
        username: username
        password: password

logging:
  config: /config/log-docker.xml
  level:
    root: warn
