spring:
  rabbitmq:
    host: mls-amqp
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass

application:
  message:
    type: tetra
    tetra:
      gateway:
        url: http://mls-message-mock-gateway:8000

logging:
  config: /config/log-docker.xml
  level:
    root: warn
