spring:
  rabbitmq:
    host: mls-amqp
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass

application:
  message:
    type: kenwood

logging:
  config: /config/log-docker.xml
  level:
    root: warn
